version: '2'
services:
    moods-app:
        image: moods
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://moods-postgresql:5432/moods
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    moods-postgresql:
        extends:
            file: postgresql.yml
            service: moods-postgresql
