version: '2'
services:
    moods-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/moods/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=moods
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
